### ISSUE TITLE
Upgrade to v0.19

### ISSUE THREAD

**Issue by toastal** [Fresheyeball/elm-return#12]
fixes #7 since infixes are axed

**Comment by toastal** [comment]
Ah, I did not bump the version number or anything like that

**Comment by wmakley** [comment]
It is still not installable in Elm 0.19. Is there anything I can help with to publish the new version? Thanks!

```sh
elm install Fresheyeball/elm-return
-- CORRUPT JSON ----------------------------------------------------------------

The elm.json for elm-community/list-extra 1.0.0 got corrupted somehow.

I removed it from my file cache, so if it was some transient error it should be
fixed if you try the same thing again. Please report this if it seems like an
Elm problem though!```

**Comment by Fresheyeball** [comment]
@wmakley can you push a PR?

**Comment by wmakley** [comment]
I'm happy to help, but it looks like you are done? Just need a bump and publish right? Or is there something left?

**Comment by Fresheyeball** [comment]
@wmakley I published. Its in elm packages

**Comment by wmakley** [comment]
Thanks, I really appreciate your work on this library! I use it in almost all my projects.
