### ISSUE TITLE
`effect` is not the best name for a function

### ISSUE THREAD

**Issue by durkiewicz** [Fresheyeball/elm-return#2]
`effect` is a keyword and therefore it's not the best name for a function. I've raised a bug in `elm-make` about it and in my opinion, the compiler should reject such code: https://github.com/elm-lang/elm-compiler/issues/1518

Until it's fixed, it would be a good practise not to use keywords as identifiers.

This keyword is used e.g. in:
https://github.com/elm-lang/core/blob/master/src/Task.elm
https://github.com/elm-lang/core/blob/master/src/Time.elm

**Comment by Fresheyeball** [comment]
So this hasn't caused any problems for me so far, but I agree that keyword overloading is a problem. What would you suggest this function be called?

**Comment by Fresheyeball** [comment]
Well let me know if you think of a better name. I changed to `effect -> effect_` for now, and published `5.0.0`. Hope that resolves your issue. :8ball:

https://github.com/Fresheyeball/elm-return/releases/tag/5.0.0
