### ISSUE TITLE
Cannot be used with Bogdanp/elm-combine

### ISSUE THREAD

**Issue by roSievers** [Fresheyeball/elm-return#6]
Your new infix operator precedences clash because of a compiler bug. I would love to use both of your libraries, can you find a way to sort that out?

Bug at elm-combine: https://github.com/Bogdanp/elm-combine/issues/19
Compiler bug: https://github.com/elm-lang/elm-compiler/issues/1096
This isn't the first time that happens to Bogdan: https://github.com/Bogdanp/elm-combine/issues/18

For anyone else with the same problem, ditching this for Bloom's fork solves the issue, because they are behind on the infix operators: http://package.elm-lang.org/packages/bloom/elm-return/latest

**Comment by Fresheyeball** [comment]
I recently merged a PR from @splodingsocks is this still an issue?

**Comment by roSievers** [comment]
The last commit was 7 days ago (except for the license) and I stumbled on the problem six days ago. The Problem are the `infixl` definitions and they [are still in your code](https://github.com/Fresheyeball/elm-return/blob/master/Infix.elm#L13). (Also, that merge does not show up for me or github doesn't know it was a merge.)

I believe the problem can't be solved without removing `infixl` declaration from either package and thus removing some functionality. That's unfortunate and I'm not saying either of you has to do that. (Especially since I have a workaround)

**Comment by Fresheyeball** [comment]
Ok

**Comment by Fresheyeball** [comment]
Here ya go. All fixed up https://github.com/Fresheyeball/elm-return/commit/6bd87ec5bd6c8d48c94ea717d8912fb800f14c22

**Comment by roSievers** [comment]
Thanks, I just tested compatibility by switching back to your version of the package. It works great.
